
name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Checking tools
      run: |
        cmake --version
        pip --version
    - name: Install Conan
      run: |
        pip install conan
    - name: Install Conan packages
      run: |
        conan install . -if build --build=missing
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build
    - name: Building
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Testing
      run: |
        cd ${{ github.workspace }}/build/tests
        ctest -C Debug --rerun-failed --output-on-failure

  build-macos:
    runs-on: macos-latest
    env:
      C_INCLUDE_PATH: "/usr/local/Cellar/cmocka/1.1.5/include"
    steps:
    - uses: actions/checkout@v2
    - name: Checking tools
      run: |
        cmake --version
        brew --version
    - name: Install Conan
      run: |
        brew install conan
    - name: Install Conan packages
      run: |
        conan install . -if build --build=missing
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build
    - name: Building
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Testing
      run: |
        cd ${{ github.workspace }}/build/tests
        ctest -C Debug --rerun-failed --output-on-failure

  build-windows:
    runs-on: windows-latest
    env:
      C_INCLUDE_PATH: "${{ github.workspace }}/cmocka/include"
      LD_LIBRARY_PATH: "${{ github.workspace }}/cmocka/bin"
    steps:
    - uses: actions/checkout@v2
    - name: Checking tools
      run: |
        cmake --version
        pip --version
    - name: Install Conan
      run: |
        pip install conan
    - name: Install Conan packages
      run: |
        conan install . -if build --build=missing
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build
    - name: Building
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Testing
      run: |
        cd ${{ github.workspace }}/build/tests
        ctest -C Debug --rerun-failed --output-on-failure
